In [1]:
import numpy as np
import scipy.signal

## 1-D

In [2]:
# This is Not Cross correlation (which does not reverse the filter)
def conv1D(x, w, p=0, s=1):
    w = w[::-1]
    if p>0:
        x = np.append(np.zeros(p),x)
        x = np.append(x,np.zeros(p))
    
    ydim = int(np.floor((len(x) - len(w))/s) + 1)

    y = np.zeros(ydim)
    i = 0    
    while(i + len(w) <= len(x)):
        y[i] = np.dot(x[i : i + len(w)],w)
        i += s
    return y
    

In [3]:
x = np.array([1,3,2,4,5,6,1,3]) # n=8
w = np.array([1,0,3,1,2]) # m=5 

# output y size --> (n + 2p - m)/s + 1

print(conv1D(x, w, p=2, s=1))


[ 5. 14. 16. 26. 24. 34. 19. 22.]


In [4]:
print(f"In-bult function's result : {np.convolve(x, w, mode='same')}")

In-bult function's result : [ 5 14 16 26 24 34 19 22]


## 2-D

In [5]:
# This is Not Cross correlation (which does not reverse the filter)
def conv2D(X, W, p=(0,0), s=(1,1)):
    W = W[::-1, ::-1]
    if (p[0] != 0):
        X = np.concatenate([np.zeros((X.shape[0],p[0])), X, np.zeros((X.shape[0],p[0]))], axis=1)
    if (p[1] != 0):
        X = np.concatenate([np.zeros((p[1],X.shape[1])), X, np.zeros((p[1],X.shape[1]))], axis=0)
    
    ydimy = int(np.floor((X.shape[0] - W.shape[0])/s[0]) + 1)
    ydimx = int(np.floor((X.shape[1] - W.shape[1])/s[1]) + 1)
    Y = np.zeros((ydimx, ydimy))
     
    for i in range(0, ydimy, s[0]):
        res = np.array([])
        for j in range(0, ydimx, s[1]):
            Y[int(i/s[0]) : int(i/s[0]) + W.shape[0], int(j/s[1]) : int(j/s[1]) + W.shape[1]] = np.sum(X[i : i + W.shape[0], j : j + W.shape[1]] * W )
    return Y

In [6]:
X = np.array([[1, 3, 2, 4], [5, 6, 1, 3], [1, 2, 0, 2], [3, 4, 3, 2]]) 
W = np.array([[1, 0, 3], [1, 2, 1], [0, 1, 1]])

print(conv2D(X, W, p=(2,2), s=(1,1)))

[[ 1.  3.  5. 13.  6. 12.]
 [ 6. 11. 25. 32. 13. 13.]
 [ 6. 19. 25. 24. 13. 13.]
 [ 4. 13. 28. 25. 17. 11.]
 [ 3. 11. 17. 14.  9.  4.]
 [ 0.  3.  7.  7.  5.  2.]]


In [7]:
print(f"SciPy results: \n{scipy.signal.convolve2d(X,W,mode='full')}")

SciPy results: 
[[ 1  3  5 13  6 12]
 [ 6 11 25 32 13 13]
 [ 6 19 25 24 13 13]
 [ 4 13 28 25 17 11]
 [ 3 11 17 14  9  4]
 [ 0  3  7  7  5  2]]
